import { createClient, createAdminClient } from '@/lib/supabase/server'
import { recordActionStart, recordActionComplete } from '@/lib/actions/execute'

export const maxDuration = 30

/**
 * POST /api/projects/[id]/phases/7/actions/new-cycle
 * Autonomous iteration: reads Phase 07 backlog → creates features in Phase 01 → starts new cycle.
 */
export async function POST(
  _request: Request,
  { params }: { params: Promise<{ id: string }> },
) {
  const { id: projectId } = await params
  const supabase = await createClient()

  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return new Response('Unauthorized', { status: 401 })

  const { data: project } = await supabase
    .from('projects')
    .select('id, cycle_number, user_id')
    .eq('id', projectId)
    .eq('user_id', user.id)
    .single()

  if (!project) return Response.json({ error: 'not_found' }, { status: 404 })

  let executionId = ''
  try {
    executionId = await recordActionStart(projectId, 7, 'backlog', 0, 'new-cycle')
  } catch { /* non-fatal */ }

  const admin = await createAdminClient()

  try {
    // Step 1: Read backlog from knowledge base (generated by Phase 07 retrospective/backlog)
    const { data: backlogEntries } = await admin
      .from('knowledge_base_entries')
      .select('title, content, summary')
      .eq('project_id', projectId)
      .in('category', ['agent_memory', 'backlog'])
      .order('created_at', { ascending: false })
      .limit(5)

    // Step 2: Extract feature names from backlog
    const featureNames: string[] = []

    for (const entry of backlogEntries ?? []) {
      const content = entry.content ?? entry.summary ?? ''
      // Look for feature-like items: lines starting with - or * or numbered
      const lines = content.split('\n')
      for (const line of lines) {
        const match = line.match(/^[-*]\s+(.{10,80})$/) ?? line.match(/^\d+\.\s+(.{10,80})$/)
        if (match && featureNames.length < 5) {
          const name = match[1].replace(/\*\*/g, '').trim()
          if (name && !featureNames.includes(name)) {
            featureNames.push(name)
          }
        }
      }
    }

    if (featureNames.length === 0) {
      if (executionId) await recordActionComplete(executionId, 'failed', undefined, undefined, 'No se encontraron features en el backlog')
      return Response.json({
        success: false,
        error: 'No se encontraron features en el backlog. Genera el backlog primero en Phase 07.',
      })
    }

    // Step 3: Create features in project_features
    const newCycleNumber = (project.cycle_number ?? 1) + 1
    const insertedFeatures: string[] = []

    for (let i = 0; i < featureNames.length; i++) {
      const { data: feature } = await admin
        .from('project_features')
        .insert({
          project_id: projectId,
          name: featureNames[i],
          description: `Feature del ciclo ${newCycleNumber}, generada automaticamente del backlog.`,
          display_order: i,
          status: 'pending',
          suggested_by: 'orchestrator',
        })
        .select('id, name')
        .single()

      if (feature) insertedFeatures.push(feature.name)
    }

    // Step 4: Increment cycle number
    await admin
      .from('projects')
      .update({ cycle_number: newCycleNumber, current_phase: 1 })
      .eq('id', projectId)

    // Step 5: Reset Phase 01 status to active
    await admin
      .from('project_phases')
      .update({ status: 'active', started_at: new Date().toISOString(), completed_at: null, approved_at: null })
      .eq('project_id', projectId)
      .eq('phase_number', 1)

    // Step 6: Save to knowledge base
    await admin.from('knowledge_base_entries').insert({
      project_id: projectId,
      title: `Ciclo ${newCycleNumber} iniciado`,
      content: `Nuevo ciclo de desarrollo iniciado con ${insertedFeatures.length} features del backlog:\n${insertedFeatures.map((f) => `- ${f}`).join('\n')}`,
      summary: `Ciclo ${newCycleNumber}: ${insertedFeatures.length} features`,
      category: 'agent_memory',
      source_type: 'agent',
      is_pinned: false,
    })

    if (executionId) {
      await recordActionComplete(executionId, 'success', `Ciclo ${newCycleNumber} iniciado con ${insertedFeatures.length} features`, {
        cycleNumber: newCycleNumber,
        features: insertedFeatures,
      })
    }

    return Response.json({
      success: true,
      cycleNumber: newCycleNumber,
      featuresCreated: insertedFeatures.length,
      features: insertedFeatures,
      message: `Ciclo ${newCycleNumber} iniciado. ${insertedFeatures.length} features creadas en Phase 01 desde el backlog.`,
    })
  } catch (error) {
    console.error('[new-cycle] Error:', error)
    if (executionId) await recordActionComplete(executionId, 'failed', undefined, undefined, String(error))
    return Response.json({ error: 'Error al crear nuevo ciclo.' }, { status: 500 })
  }
}
