'use client'

import { useState, useCallback } from 'react'
import type { ActionDefinition, ActionExecution } from '@/types/action'
import { getActionsForPhase } from '@/lib/actions/action-registry'

type UsePhaseActionsReturn = {
  actions: ActionDefinition[]
  executions: ActionExecution[]
  executingAction: string | null
  streamingContent: string | null
  generatedFiles: { path: string; content: string }[] | null
  executeAction: (actionName: string, extra?: Record<string, unknown>) => Promise<void>
  commitGeneratedFiles: (actionName: string) => Promise<{ success: boolean; url?: string }>
  resetStreaming: () => void
}

export function usePhaseActions(
  projectId: string,
  phaseNumber: number,
  initialExecutions: ActionExecution[] = [],
): UsePhaseActionsReturn {
  const actions = getActionsForPhase(phaseNumber)
  const [executions, setExecutions] = useState<ActionExecution[]>(initialExecutions)
  const [executingAction, setExecutingAction] = useState<string | null>(null)
  const [streamingContent, setStreamingContent] = useState<string | null>(null)
  const [generatedFiles, setGeneratedFiles] = useState<{ path: string; content: string }[] | null>(null)

  const resetStreaming = useCallback(() => {
    setStreamingContent(null)
    setGeneratedFiles(null)
  }, [])

  const executeAction = useCallback(
    async (actionName: string, extra?: Record<string, unknown>) => {
      setExecutingAction(actionName)
      setStreamingContent(null)
      setGeneratedFiles(null)

      try {
        const res = await fetch(
          `/api/projects/${projectId}/phases/${phaseNumber}/actions/${actionName}`,
          {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(extra ?? {}),
          },
        )

        const contentType = res.headers.get('content-type') ?? ''

        if (contentType.includes('text/plain') || contentType.includes('text/event-stream')) {
          // Streaming response
          const reader = res.body?.getReader()
          if (!reader) return

          const decoder = new TextDecoder()
          let accumulated = ''

          while (true) {
            const { done, value } = await reader.read()
            if (done) break
            accumulated += decoder.decode(value, { stream: true })
            setStreamingContent(accumulated)
          }

          // After streaming completes, try to parse files from the content
          // The server may send a JSON trailer with extracted files
          const jsonTrailerMatch = accumulated.match(/\n---RESULT---\n([\s\S]+)$/)
          if (jsonTrailerMatch) {
            try {
              const result = JSON.parse(jsonTrailerMatch[1])
              if (result.files) setGeneratedFiles(result.files)
              if (result.execution) {
                setExecutions((prev) => [result.execution, ...prev])
              }
              setStreamingContent(accumulated.replace(/\n---RESULT---\n[\s\S]+$/, ''))
            } catch { /* ignore parse errors */ }
          }
        } else {
          // JSON response
          const data = await res.json()
          if (data.execution) {
            setExecutions((prev) => [data.execution, ...prev])
          }
          if (data.files) {
            setGeneratedFiles(data.files)
          }
        }
      } catch (e) {
        console.error('[usePhaseActions] Error:', e)
      } finally {
        setExecutingAction(null)
      }
    },
    [projectId, phaseNumber],
  )

  const commitGeneratedFiles = useCallback(
    async (actionName: string) => {
      if (!generatedFiles || generatedFiles.length === 0) {
        return { success: false }
      }

      try {
        const res = await fetch(`/api/projects/${projectId}/commits/apply`, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            files: generatedFiles,
            message: `feat: auto-generated by ${actionName}`,
          }),
        })

        const data = await res.json()
        if (res.ok && data.sha) {
          // Notify the action endpoint that files were committed
          await fetch(
            `/api/projects/${projectId}/phases/${phaseNumber}/actions/${actionName}`,
            {
              method: 'POST',
              headers: { 'Content-Type': 'application/json' },
              body: JSON.stringify({ confirm: true, commitSha: data.sha }),
            },
          )
          return { success: true, url: data.url }
        }
        return { success: false }
      } catch {
        return { success: false }
      }
    },
    [projectId, phaseNumber, generatedFiles],
  )

  return {
    actions,
    executions,
    executingAction,
    streamingContent,
    generatedFiles,
    executeAction,
    commitGeneratedFiles,
    resetStreaming,
  }
}
