-- Marketing module tables for admin backoffice
-- Used by the Marketing Strategist agent for Tribux's own commercial strategy

-- Chat threads with the marketing agent
create table marketing_chat_threads (
  id uuid primary key default gen_random_uuid(),
  title text,
  mode text not null default 'brand'
    check (mode in ('brand', 'gtm', 'content', 'growth', 'sales', 'competitive')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Messages within marketing chat threads
create table marketing_chat_messages (
  id uuid primary key default gen_random_uuid(),
  thread_id uuid not null references marketing_chat_threads(id) on delete cascade,
  role text not null check (role in ('user', 'assistant')),
  content text not null,
  created_at timestamptz not null default now()
);

create index idx_marketing_messages_thread on marketing_chat_messages(thread_id, created_at);

-- Strategic artifacts generated by the marketing agent
create table marketing_artifacts (
  id uuid primary key default gen_random_uuid(),
  thread_id uuid references marketing_chat_threads(id) on delete set null,
  title text not null,
  type text not null
    check (type in ('brand_strategy', 'gtm_plan', 'content_strategy', 'growth_experiment', 'sales_playbook', 'competitive_messaging')),
  content text not null,
  status text not null default 'draft'
    check (status in ('draft', 'approved', 'archived')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index idx_marketing_artifacts_type on marketing_artifacts(type);
create index idx_marketing_artifacts_status on marketing_artifacts(status);

-- RLS: only admins can access marketing tables
alter table marketing_chat_threads enable row level security;
alter table marketing_chat_messages enable row level security;
alter table marketing_artifacts enable row level security;

-- Policy: financial_admin or super_admin can do everything
create policy "Admin full access on marketing_chat_threads"
  on marketing_chat_threads for all
  using (
    exists (
      select 1 from user_profiles
      where user_profiles.id = auth.uid()
      and user_profiles.role in ('financial_admin', 'super_admin')
    )
  );

create policy "Admin full access on marketing_chat_messages"
  on marketing_chat_messages for all
  using (
    exists (
      select 1 from user_profiles
      where user_profiles.id = auth.uid()
      and user_profiles.role in ('financial_admin', 'super_admin')
    )
  );

create policy "Admin full access on marketing_artifacts"
  on marketing_artifacts for all
  using (
    exists (
      select 1 from user_profiles
      where user_profiles.id = auth.uid()
      and user_profiles.role in ('financial_admin', 'super_admin')
    )
  );
